apiVersion: v1
kind: Pod
metadata:
  name: nifi
  annotations:
    # Ensures container runs with the same UID/GID as the pod creator (miadmin)
    io.podman.annotations.userns: keep-id

spec:
  restartPolicy: Never

  containers:
    - name: nifi
      #image: apache/nifi:latest
      #image: localhost/nifi-custom:2.6.0-fips-bc
      image: localhost/nifi-custom:2.6.0-fips-bc

      # Security context forces UID/GID matching miadmin (1001)
      #securityContext:
      #  runAsUser: 1001
      #  runAsGroup: 1001

      env:
        - name: NIFI_WEB_HTTPS_PORT
          value: "8443"
        - name: SINGLE_USER_CREDENTIALS_USERNAME
          value: "admin"
        - name: SINGLE_USER_CREDENTIALS_PASSWORD
          value: "!Changeme12345"
        - name: NIFI_WEB_PROXY_HOST
          value: "nifi3.ogs18.ogs.mi.ds.army.smil.mil"
      ports:
        - containerPort: 8443
          hostPort: 8443
      volumeMounts:
        - name: nifi-flowfile-repo
          mountPath: /opt/nifi/nifi-current/flowfile_repository
        - name: nifi-database-repo
          mountPath: /opt/nifi/nifi-current/database_repository
        - name: nifi-content-repo
          mountPath: /opt/nifi/nifi-current/content_repository

#having the config files presented on the host, is just not worth the problems it makes            
#        - name: nifi-conf
#          mountPath: /opt/nifi/nifi-current/conf

#        - name: shared-storage
#          mountPath: /shared-storage

#        - name: configs
          #mountPath: /tmp/nifi.properties
#          mountPath: /tmp/nifi.properties
#          subPath: nifi.properties

  volumes:
    - name: nifi-flowfile-repo
      hostPath:
        path: /mission-share/podman/containers/nifi/nifi-current/flowfile_repository
        type: DirectoryOrCreate
    - name: nifi-database-repo
      hostPath:
        path: /mission-share/podman/containers/nifi/nifi-current/database_repository
        type: DirectoryOrCreate
    - name: nifi-content-repo
      hostPath:
        path: /mission-share/podman/containers/nifi/nifi-current/content_repository
        type: DirectoryOrCreate

#    - name: nifi-conf
#      hostPath:
#        path: /mission-share/podman/containers/nifi/nifi-current/conf
#        type: DirectoryOrCreate

#    - name: shared-storage
#      hostPath:
#        path: /mission-share/podman/containers
#        type: DirectoryOrCreate
#    - name: configs
#      hostPath:
#        path: /mission-share/podman/containers/configs
#        type: DirectoryOrCreate

